services:
  # Servicio para MySQL
  db:
    image: mysql:8.0
    container_name: mysql-base
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: miublog
      MYSQL_USER: miublog
      MYSQL_PASSWORD: miublog
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3


  # Servicio para Spring Boot usando imagen desde Docker Hub
#  app:
#    image: leone2015/elibrarywebapp0-app:1.0.0
#    container_name: elibrarywebapp
#    environment:
#      DB_HOST: "db"
#      DB_NAME: "swe_lesson8"
#      DB_USERNAME: "lesson8"
#      DB_PASSWORD: "lesson8"
#      DB_PORT: "3306"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    networks:
#      - elibrary-network

networks:
  miublog-network:
    driver: bridge

volumes:
  db_data:
