# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes
#-Dfile.encoding=UTF-8
#Application Configuration
jwt:
  secret: "mysupersecretkeythatshouldbe32bytes1234"
server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always
# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: false
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/miublog?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: miublog
    password: miublog

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
        connection:
          useUnicode: true
          characterEncoding: utf8mb4
          charSet: utf8mb4
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
